apiVersion: apps/v1
kind: Deployment
metadata:
  name: laboratory-service
  labels:
    app: laboratory-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: laboratory-service
  template:
    metadata:
      labels:
        app: laboratory-service
    spec:
      containers:
      - name: laboratory-service
        image: gavya/laboratory-service:latest
        ports:
        - containerPort: 8106
        envFrom:
        - configMapRef:
            name: laboratory-service-config
        - secretRef:
            name: laboratory-service-secret
        readinessProbe:
          httpGet:
            path: /healthz
            port: 8106
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8106
          initialDelaySeconds: 15
          periodSeconds: 20
        resources:
          requests:
            cpu: "200m"
            memory: "256Mi"
          limits:
            cpu: "1000m"
            memory: "512Mi"
