package repository

import (
	"context"
	"errors"
	"fmt"

	"github.com/jackc/pgx/v5/pgconn"

	"github.com/ppusapati/gavya/services/inventory-service/internal/domain"
)

// ErrInsufficientStock is a movement that would leave less than nothing on the
// shelf. It is named so the caller learns the movement was refused rather than
// that something went wrong.
var ErrInsufficientStock = errors.New("insufficient stock")

// ErrUnknownWarehouse is the foreign key on inventory_items. Without it a
// movement against a warehouse that does not exist is reported as an internal
// failure, and the caller is told to try again rather than to fix the id.
var ErrUnknownWarehouse = errors.New("no such warehouse")

// MovementOutcome is the movement as written and the stock it left behind.
type MovementOutcome struct {
	Movement *domain.StockMovement
	Item     *domain.InventoryItem
}

// ApplyStockMovement records one movement and moves the stock it describes, in
// a single transaction.
//
// This replaced a read-modify-write across three separate round trips. That
// version had four ways of getting stock wrong, and this exists to close all
// four:
//
//   - Two concurrent movements both read the same quantity and both wrote their
//     own total, so one of them was silently lost. The row is now locked for the
//     length of the transaction and the arithmetic happens in the database.
//   - A failed read was treated as "no such item", which set the quantity to
//     zero and then applied the movement — a connection blip destroyed stock.
//     A failed read is now a failure.
//   - The movement was written first and the quantity updated afterwards, with
//     the update's error logged and swallowed. A caller was told the adjustment
//     had succeeded when the stock had not moved. Both writes now commit
//     together or neither does.
//   - Arithmetic in float64 against a NUMERIC(12,3) column accumulated error
//     over a stock item's life. Every sum is now done by the database, in the
//     column's own type.
//
// quantity is a decimal literal rather than a float, so what the caller asked
// for is what the database adds. itemID names the stock row if this SKU has
// never been held at this warehouse; it is generated by the caller so nothing
// inside the transaction depends on when the transaction runs.
func (r *repo) ApplyStockMovement(ctx context.Context, m *domain.StockMovement, quantity, itemID string) (*MovementOutcome, error) {
	tx, err := r.pool.Begin(ctx)
	if err != nil {
		return nil, fmt.Errorf("begin: %w", err)
	}
	defer tx.Rollback(ctx)

	// Take the row, creating it if this SKU has never been stocked here. An
	// upsert that updates nothing still locks the row it conflicts with, which
	// is what serialises two movements against the same shelf.
	current, err := scanInventoryItem(tx.QueryRow(ctx,
		`INSERT INTO inventory_items (id,tenant_id,warehouse_id,sku_id,created_by,updated_by)
		 VALUES ($1,$2,$3,$4,$5,$5)
		 ON CONFLICT (tenant_id,warehouse_id,sku_id) DO UPDATE SET updated_at=inventory_items.updated_at
		 RETURNING `+inventoryItemCols,
		itemID, m.TenantID, m.WarehouseID, m.SKUID, m.CreatedBy))
	if err != nil {
		if isForeignKeyViolation(err) {
			return nil, ErrUnknownWarehouse
		}
		return nil, fmt.Errorf("lock stock: %w", err)
	}

	// The guard in the WHERE clause is what refuses the movement. Evaluating it
	// in the same statement that applies the change means there is no instant
	// between the check and the write for another movement to occupy.
	var set, guard string
	switch m.MovementType {
	case domain.MovementIn:
		set, guard = `quantity_on_hand + $4::numeric`, `quantity_on_hand + $4::numeric >= 0`
	case domain.MovementOut, domain.MovementTransfer:
		set, guard = `quantity_on_hand - $4::numeric`, `quantity_on_hand - $4::numeric >= 0`
	case domain.MovementAdjustment:
		// An adjustment states the count after a stocktake, so it replaces the
		// running total rather than moving it.
		set, guard = `$4::numeric`, `$4::numeric >= 0`
	default:
		return nil, fmt.Errorf("unknown movement type %q", m.MovementType)
	}

	item, err := scanInventoryItem(tx.QueryRow(ctx,
		`UPDATE inventory_items
		 SET quantity_on_hand = `+set+`, last_updated_at=NOW(), updated_at=NOW(), updated_by=$5
		 WHERE tenant_id=$1 AND warehouse_id=$2 AND sku_id=$3 AND `+guard+`
		 RETURNING `+inventoryItemCols,
		m.TenantID, m.WarehouseID, m.SKUID, quantity, m.UpdatedBy))
	if err != nil {
		// The row was locked a moment ago and cannot have vanished, so the only
		// way it fails to match now is the guard.
		if errors.Is(err, ErrNotFound) {
			return nil, fmt.Errorf("%w: %s on hand, %s of %s refused",
				ErrInsufficientStock, domain.FormatStock(current.QuantityOnHand), m.MovementType, quantity)
		}
		return nil, fmt.Errorf("move stock: %w", err)
	}

	movement, err := scanStockMovement(tx.QueryRow(ctx,
		`INSERT INTO stock_movements
		   (id,tenant_id,warehouse_id,sku_id,movement_type,quantity,reference_id,reference_type,notes,moved_at,moved_by,created_by,updated_by)
		 VALUES ($1,$2,$3,$4,$5,$6::numeric,$7,$8,$9,$10,$11,$12,$13)
		 RETURNING `+stockMovementCols,
		m.ID, m.TenantID, m.WarehouseID, m.SKUID, string(m.MovementType), quantity,
		m.ReferenceID, m.ReferenceType, m.Notes, m.MovedAt, m.MovedBy, m.CreatedBy, m.UpdatedBy))
	if err != nil {
		return nil, fmt.Errorf("record movement: %w", err)
	}

	if err := tx.Commit(ctx); err != nil {
		return nil, fmt.Errorf("commit: %w", err)
	}
	return &MovementOutcome{Movement: movement, Item: item}, nil
}

func isForeignKeyViolation(err error) bool {
	var pgErr *pgconn.PgError
	return errors.As(err, &pgErr) && pgErr.Code == "23503"
}
